site_name: Tagz documentation
nav:
    - Home: index.md
    - About: about.md
    - Reference: reference.md
theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.png

plugins:
    - search
    - mkdocstrings